export const meta = {
  name: 'interactive-scenes',
  description: 'Add interactive scene features: source management, drag reorder, keyboard shortcuts, transition controls',
  phases: [
    { title: 'Backend', detail: 'OBS source visibility endpoints' },
    { title: 'Frontend', detail: 'Interactive SceneSwitcher rewrite' },
  ],
};

const apiTypes = [
  'export interface SceneSource {',
  '  id: number;',
  '  name: string;',
  '  enabled: boolean;',
  '  type: string;',
  '  parent_group?: string;',
  '}',
  '',
  'export interface ToggleResponse {',
  '  source_id: number;',
  '  enabled: boolean;',
  '}',
].join('\n');

// ══════════════════════════════════════════════════════════════════════
// Phase 1: Backend - add source visibility endpoints
// ══════════════════════════════════════════════════════════════════════
phase('Backend');
log('Adding scene source visibility endpoints to OBS controller + API...');

await agent(
  [
    'You are a Backend Architect. Add scene source management endpoints to the Broadcast OS backend.',
    '',
    'Files to read:',
    '- obs/controller.py',
    '- api/routes.py',
    '- api/schemas.py',
    '',
    '=== 1. obs/controller.py ===',
    'Add two methods:',
    '',
    'async def get_scene_sources(self, scene_name: str) -> list[dict]:',
    '  - Uses obs_requests.GetSceneItemList(sceneName=scene_name)',
    '  - Returns a list of dicts: { "id": sceneItemId, "name": sourceName, "enabled": sceneItemEnabled, "type": sourceType or "unknown" }',
    '  - On error, raises ObsConnectionError',
    '',
    'async def set_source_visibility(self, scene_name: str, source_id: int, enabled: bool) -> bool:',
    '  - Uses obs_requests.SetSceneItemEnabled(sceneName=scene_name, sceneItemId=source_id, sceneItemEnabled=enabled)',
    '  - Returns True on success',
    '  - Raises ObsConnectionError on failure',
    '',
    'Note: There is already a set_source_visibility method (line 109) that works on the current scene by source name.',
    'Keep that one. Add a NEW version that works by scene_name + scene_item_id for any scene.',
    '',
    '=== 2. api/schemas.py ===',
    'Read the file, then add these Pydantic models:',
    '',
    'class SceneSourceResponse(BaseModel):',
    '  id: int',
    '  name: str',
    '  enabled: bool',
    '  type: str',
    '',
    'class SourceToggleResponse(BaseModel):',
    '  source_id: int',
    '  enabled: bool',
    '',
    '=== 3. api/routes.py ===',
    'Import SceneSourceResponse, SourceToggleResponse at the top',
    '',
    'Add two new endpoints inside the existing /broadcast router:',
    '',
    'GET /broadcast/scenes/{scene_name}/sources',
    '  - Returns list of SceneSourceResponse',
    '  - Calls _obs.get_scene_sources(scene_name)',
    '  - Returns 503 if OBS not connected',
    '',
    'POST /broadcast/scenes/{scene_name}/sources/{source_id}/toggle',
    '  - Gets current sources, finds the one matching source_id, determines new enabled state (not the current enabled)',
    '  - Calls _obs.set_source_visibility(scene_name, source_id, new_enabled_state)',
    '  - Returns SourceToggleResponse',
    '  - Returns 503 if OBS not connected, 404 if source not found',
    '',
    'IMPORTANT: Edit the existing files. Do NOT create new files. Use the Edit tool on the existing files.',
    'After making all changes, verify the syntax is valid Python (no undefined names, correct imports).',
    'Keep all existing code intact.',
  ].join('\n'),
  {
    agentType: 'Backend Architect',
    effort: 'high',
    label: 'backend-sources',
  },
);

// ══════════════════════════════════════════════════════════════════════
// Phase 2: Frontend - interactive SceneSwitcher
// ══════════════════════════════════════════════════════════════════════
phase('Frontend');
log('Rewriting SceneSwitcher with full interactivity...');

await agent(
  [
    'You are a UI Designer specializing in interactive production tools.',
    'Rewrite the SceneSwitcher component and add scene source API functions.',
    '',
    'Files to read:',
    '- dashboard/src/lib/api.ts (read the full file to understand existing patterns, especially getScenes and switchScene)',
    '- dashboard/src/components/SceneSwitcher.tsx (read the full current file)',
    '- dashboard/src/index.css (to understand available design tokens)',
    '',
    'Files to write/modify:',
    '',
    '=== 1. dashboard/src/lib/api.ts ===',
    'Add these interfaces and functions at the bottom (before the Analytics section or at the end):',
    '',
    apiTypes,
    '',
    'export async function getSceneSources(sceneName: string): Promise<SceneSource[]> {',
    '  const res = await fetch(`${API_BASE}/broadcast/scenes/${encodeURIComponent(sceneName)}/sources`);',
    '  if (!res.ok) throw new Error("Failed to fetch scene sources");',
    '  return res.json();',
    '}',
    '',
    'export async function toggleSource(sceneName: string, sourceId: number): Promise<ToggleResponse> {',
    '  const res = await fetch(',
    '    `${API_BASE}/broadcast/scenes/${encodeURIComponent(sceneName)}/sources/${sourceId}/toggle`,',
    '    { method: "POST" }',
    '  );',
    '  if (!res.ok) throw new Error("Failed to toggle source");',
    '  return res.json();',
    '}',
    '',
    '=== 2. dashboard/src/components/SceneSwitcher.tsx ===',
    'Rewrite the COMPLETE file with these features:',
    '',
    'LAYOUT & VISUAL:',
    '- Scene buttons become interactive CARDS with colored backgrounds:',
    '  * Each scene card shows a large colored block (use different hues from the design system)',
    '  * PGM (program) scene card: red left border, shows "ON AIR" badge',
    '  * PVW (preview) scene card: green left border, shows "NEXT" badge',
    '  * Regular scenes: neutral dark card appearance',
    '  * Scene name displayed prominently on each card',
    '  * Cards are in a responsive grid (auto-fill, min 180px)',
    '',
    'DRAG & DROP REORDERING:',
    '- Add drag handles (grip dots SVG) to each scene card',
    '- On drag end, reorder the local scenes array and save to localStorage("sceneOrder")',
    '- Visual feedback during drag: elevated shadow, slight opacity',
    '',
    'SOURCE MANAGEMENT:',
    '- Clicking a scene card TOGGLES an expanded source panel below it',
    '- The source panel shows all sources in that scene with:',
    '  * Source name',
    '  * Source type badge',
    '  * Visibility toggle (eye icon button)',
    '  * Toggle calls toggleSource API and updates local state',
    '- Source panel has bg-elevated background',
    '- Loading/error states for source fetch',
    '',
    'KEYBOARD SHORTCUTS:',
    '- Listen for keydown events on the component container',
    '- Keys 1 through 9: select the scene at that index as preview',
    '- Enter or T key: trigger Take (if a preview scene is selected)',
    '- R key: refresh scene list',
    '- Escape key: clear preview selection',
    '- Show a small keyboard shortcuts hint section at the bottom',
    '',
    'TRANSITION CONTROLS:',
    '- Transition type selector (keep existing Cut/Mix/Fade radio group)',
    '- ADD a transition duration slider (0-2000ms) with label showing current value',
    '- The duration is local state (not sent to API yet)',
    '- Label: "Duration" with value in ms',
    '',
    'TAKE ANIMATION:',
    '- When Take is pressed, the PGM scene card briefly flashes (scale pulse or glow)',
    '- Use a CSS animation class that triggers on take, auto-removes after 500ms',
    '',
    'HOVER & INTERACTION:',
    '- Scene cards have hover effects (brighten, slight lift)',
    '- Click feedback (instant visual response)',
    '- Smooth transitions on all state changes',
    '',
    'STATES:',
    '- Loading: skeleton scene cards',
    '- Empty: "No scenes available" with instructions',
    '- Error (OBS disconnected): warning with retry button',
    '- Transient errors: toast-style error banner',
    '',
    'USE the design system classes: bg-surface, bg-elevated, bg-base, border, text, text-secondary, text-muted, brand, live, danger, accent, card, btn, btn-primary, btn-ghost, input-field, section-header, badge, live-dot, animate-fade-in, etc.',
    '',
    'IMPORTANT: Rewrite the ENTIRE SceneSwitcher.tsx file. Preserve the existing imports (getScenes, switchScene) and add the new ones (getSceneSources, toggleSource). All original functionality must work AND all new features must work.',
  ].join('\n'),
  {
    agentType: 'UI Designer',
    effort: 'high',
    label: 'frontend-scenes',
  },
);

log('Interactive scenes complete! Backend endpoints added + frontend SceneSwitcher rewritten.');
